const ACTION_TYPE = {
  TABLE_RESIZE: 'TABLE_RESIZE',
  CHANGE_TEXT: 'CHANGE_TEXT',
  APPLY_STYLE: 'APPLY_STYLE',
  CHANGE_STYLES: 'CHANGE_STYLES',
  HEADER_TEXT: 'HEADER_TEXT',
};

export {ACTION_TYPE};
